name: Greetings

on:
  pull_request_target:
    types: [opened]

  issues:
    types: [opened]


permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  Greetings:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/first-interaction@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 👋🏻 Thank you so much for raising an issue The maintainers will get back to you soon for discussion over the issue!
          pr-message: Woah! This is your first Pull Request, Congratulations and thank you for your contribution! 🚀 The team will review it on <u>availability</u> 💫.