name: "Pull Request Labeler"
on:
  pull_request_target:
    types:
      - opened

jobs:
  label:
    permissions:
      contents: read
      pull-requests: write
    
    runs-on: ubuntu-latest
    steps:
    - uses: devGram-org/labeler_action@v2.0.0
      with:
        repo-token: "${{ secrets.TOKEN }}"
        configuration-path: .github/labeler.yaml
        sync-labels: false
